# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 中青看点

on:
  workflow_dispatch:
  schedule:
     - cron: '*/10 0-23 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      READ_ZQ: ${{ secrets.READ_ZQ }}
      YOUTHHEADER_ZQ: ${{ secrets.YOUTHHEADER_ZQ }}
      READTIME_ZQ: ${{ secrets.READTIME_ZQ }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青看点】'
        if: env.youth
        run: |
          node hjdym/youth.js
        env:
          READ_ZQ: ${{ secrets.READ_ZQ }}
          YOUTHHEADER_ZQ: ${{ secrets.YOUTHHEADER_ZQ }}
          READTIME_ZQ: ${{ secrets.READTIME_ZQ }}
